### ISSUE TITLE
Taginfo embed triggers internal error on wiki

### ISSUE THREAD

**Issue by 1ec5** [Firefishy/osmtaginfo#3]
As of 0a2a0285a9f46d533bd8174bda3a0d3ce13b0bf3, any invocation of the `osmtaginfo` parser tag causes an internal error, preventing the page from loading:

```
{{#tag:osmtaginfo||key=highway|value=trunk}}
```

For example, [“Tag:highway=trunk”](https://wiki.openstreetmap.org/wiki/Tag:highway=trunk) shows:

> [12de562be3087382509719a9] 2022-01-02 20:30:54: Fatal exception of type "Error"

Pages that embed the AJAX-powered replacement, [`taginfo2`](https://wiki.openstreetmap.org/wiki/Template:Taginfo2), are unaffected.

(Reported by @jleedev in [OSMUS Slack](https://osmus.slack.com/archives/C1R62SM9T/p1641152361038900).)

/cc @Firefishy @tomhughes

**Comment by ZeLonewolf** [comment]
Are there any objections at this point to dropping the current iframe-based osmtaginfo and instead making a drop-in replacement of taginfo2?  This could be done entirely within wiki-space and this repo could be archived.

**Comment by tomhughes** [comment]
I have no objections to anything because I mostly have no idea what I'm doing here.

I don't understand the error though because I tested a page that uses the extension after I deployed the update and it was fine...

**Comment by tomhughes** [comment]
Looks like this is the error:

```
[exception] [5aeee21f2e2e7806934d8ede] /wiki/Tag:highway%3Dtrunk   Error from line 40 of /srv/wiki.openstreetmap.org/w/extensions/osmtaginfo/osmtaginfo.class.php: Call to undefined function wfLoadExtensionMessages()
#0 /srv/wiki.openstreetmap.org/w/includes/parser/Parser.php(3922): OSMTagInfo::parse()
#1 /srv/wiki.openstreetmap.org/w/includes/parser/CoreParserFunctions.php(1127): Parser->extensionSubstitution()
#2 /srv/wiki.openstreetmap.org/w/includes/parser/Parser.php(3340): CoreParserFunctions::tagObj()
#3 /srv/wiki.openstreetmap.org/w/includes/parser/Parser.php(3047): Parser->callParserFunction()
#4 /srv/wiki.openstreetmap.org/w/includes/parser/PPFrame_Hash.php(263): Parser->braceSubstitution()
#5 /srv/wiki.openstreetmap.org/w/extensions/ParserFunctions/includes/ParserFunctions.php(121): PPFrame_Hash->expand()
#6 /srv/wiki.openstreetmap.org/w/includes/parser/Parser.php(3340): MediaWiki\Extensions\ParserFunctions\ParserFunctions::if()
#7 /srv/wiki.openstreetmap.org/w/includes/parser/Parser.php(3047): Parser->callParserFunction()
#8 /srv/wiki.openstreetmap.org/w/includes/parser/PPFrame_Hash.php(263): Parser->braceSubstitution()
#9 /srv/wiki.openstreetmap.org/w/extensions/ParserFunctions/includes/ParserFunctions.php(121): PPFrame_Hash->expand()
#10 /srv/wiki.openstreetmap.org/w/includes/parser/Parser.php(3340): MediaWiki\Extensions\ParserFunctions\ParserFunctions::if()
#11 /srv/wiki.openstreetmap.org/w/includes/parser/Parser.php(3047): Parser->callParserFunction()
#12 /srv/wiki.openstreetmap.org/w/includes/parser/PPFrame_Hash.php(263): Parser->braceSubstitution()
#13 /srv/wiki.openstreetmap.org/w/extensions/ParserFunctions/includes/ParserFunctions.php(227): PPFrame_Hash->expand()
#14 /srv/wiki.openstreetmap.org/w/includes/parser/Parser.php(3340): MediaWiki\Extensions\ParserFunctions\ParserFunctions::switch()
#15 /srv/wiki.openstreetmap.org/w/includes/parser/Parser.php(3047): Parser->callParserFunction()
#16 /srv/wiki.openstreetmap.org/w/includes/parser/PPFrame_Hash.php(263): Parser->braceSubstitution()
````

**Comment by tomhughes** [comment]
Fixed in https://github.com/Firefishy/osmtaginfo/commit/5175fec9323ed9148e17a679532070245fd0eb66.

**Comment by 1ec5** [comment]
Thanks for the quick fix! [I started another discussion on the wiki](https://wiki.openstreetmap.org/wiki/Talk:Wiki#Migrate_taginfo_to_AJAX-based_rewrite) about sunsetting this extension so we don’t have to maintain two different versions.
